### PR TITLE
Override the experimental warning screen with opt-out.

### PR DESCRIPTION
**Pull request by LambdAurora**

### CODE REVIEW

**Review by peaceheis — APPROVED** [review]
This is a small change, but it would be really useful for worldgeners and players in general.

**Review by TheGlitch76 — APPROVED** [review]

**Review by Leo40Git — APPROVED** [review]

**Review by EnnuiL — APPROVED** [review]

**Comment by oliviathevampire** [comment]
Is this even needed in 1.19?

**Comment by LambdAurora** [comment]
> Is this even needed in 1.19?

The PR targets 1.18, but the issue is still very well present in 1.19.

**Comment by oliviathevampire** [comment]
> > Is this even needed in 1.19?
> 
> The PR targets 1.18, but the issue is still very well present in 1.19.

I've looked through the code and can't seem to find the same place it mixins, seems like WorldLoadAction might have been removed

**Pull request merged**
