### PR TITLE
1.19.4 feature backports 

### PR DESCRIPTION
**Pull request by rinOfTheStars**
Backports the following changes required for or related to QFAPI sync:
- https://github.com/QuiltMC/quilt-standard-libraries/commit/2ff57f22e8dd610dcb2cfe234452c8319a0fc01b
- https://github.com/QuiltMC/quilt-standard-libraries/pull/330
- https://github.com/QuiltMC/quilt-standard-libraries/pull/329
- https://github.com/quiltmc/quilt-standard-libraries/commit/a8991ca686397828301b9d62d7289ecdc5707381
- https://github.com/quiltmc/quilt-standard-libraries/commit/c63c4893af453974f3798e9315cb05cb0a03b35a

Also ran the licenser, which created... _quite the few file changes_ that were just updating copyright year numbers. Tell me if I should revert that or not, please.

If there's more that needs to be done _please let me know_, this is a draft PR for a reason—I'm not sure if I caught everything that's absolutely necessary!

### CODE REVIEW

**Comment by OroArmor** [comment]
Are you on windows? That messes up the licenser. If you revert the commit i can push a commit with the correct headers.

**Comment by rinOfTheStars** [comment]
> Are you on windows? That messes up the licenser

nope, I'm on macOS, and it's worked fine in the past. If the headers are malformated in this case too, it might be a more general issue with the copyright year incrementing function? 
Also, looking at the headers they all look fine, as mentioned prior it's almost all just updating the copyright year range to contain 2023

**Comment by OroArmor** [comment]
Hm interesting. Not sure at all, but yeah i would revert that last commit for now

**Review by OroArmor — APPROVED** [review]

**Comment by EnnuiL** [comment]
> > Are you on windows? That messes up the licenser
> 
> nope, I'm on macOS, and it's worked fine in the past. If the headers are malformated in this case too, it might be a more general issue with the copyright year incrementing function? Also, looking at the headers they all look fine, as mentioned prior it's almost all just updating the copyright year range to contain 2023

The fix would be to backport the license header change, since yeah, the range is a lost cause

**Comment by rinOfTheStars** [comment]
> > > Are you on windows? That messes up the licenser
> > 
> > 
> > nope, I'm on macOS, and it's worked fine in the past. If the headers are malformated in this case too, it might be a more general issue with the copyright year incrementing function? Also, looking at the headers they all look fine, as mentioned prior it's almost all just updating the copyright year range to contain 2023
> 
> The fix would be to backport the license header change, since yeah, the range is a lost cause

Ah, uh, how would that be done? Discussion is going on when it comes to licenser bs in the discord as well fyi, that's probably a better place to handle this technicality specifically.

**Comment by rinOfTheStars** [comment]
Other than the licenser issues, this should be good to go ahead. Going to make it into a normal PR.

**Review by EnnuiL — APPROVED** [review]

**Pull request merged**
