### PR TITLE
Use QuiltLoader.createModTable instead of manually generating the mod list

### PR DESCRIPTION
**Pull request by AlexIIL**
This means QSL will automatically gain information about newer loader features (like what plugin loaded a given mod) when loader-plugins is released, and will add source paths too (also when loader plugins are released).

An example output (taken from *loader*, since I am having trouble building QSL locally :/ )
```
| Index | Mod                      | ID                                                        | Version  |
|------:|--------------------------|-----------------------------------------------------------|----------|
|    19 | GroovyDuvet: Core        | groovyduvet_core                                          | 1.0.2    |
|    17 | Minecraft                | minecraft                                                 | 1.19.2   |
|    18 | OpenJDK 64-Bit Server VM | java                                                      | 18       |
|    20 | Quilt Loader             | quilt_loader                                              | 0.17.4   |
|     9 | groovy                   | org_apache_groovy_groovy                                  | 4.0.4    |
|     8 | jackson-databind         | com_fasterxml_jackson_core_jackson-databind               | 2.13.3   |
|    12 | jackson-dataformat-toml  | com_fasterxml_jackson_dataformat_jackson-dataformat-toml  | 2.13.3   |
|     5 | mapping-io               | net_fabricmc_mapping-io                                   | 0.3.0    |
|------:|--------------------------|-----------------------------------------------------------|----------|
```
Since loader-plugins is in development the mod table will look something like this when it's merged (and the user is using it - with no other code changes to QSL required):
```
| Mod                                   | ID                                     | Version               | Plugin                 | File(s)                                                                                                                                                                         | Sub-Files                                                          | Sub-Files                                                       | Sub-Files                                       | Sub-Files                                     | Sub-Files                                     |
|---------------------------------------|----------------------------------------|-----------------------|------------------------|---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|--------------------------------------------------------------------|-----------------------------------------------------------------|-------------------------------------------------|-----------------------------------------------|-----------------------------------------------|
| Cardinal Components API (base)        | cardinal-components-base               | 5.0.1                 | quilted_fabric_loader  | <mods>/twilightforest-fabric-1.19.2-4.2.299.jar                                                                                                                                 | /META-INF/jars/cardinal-components-base-5.0.1.jar                  |                                                                 |                                                 |                                               |                                               |
| Cardinal Components API (entities)    | cardinal-components-entity             | 5.0.1                 | quilted_fabric_loader  | <mods>/twilightforest-fabric-1.19.2-4.2.299.jar                                                                                                                                 | /META-INF/jars/cardinal-components-entity-5.0.1.jar                |                                                                 |                                                 |                                               |                                               |
| Minecraft                             | minecraft                              | 1.18.2                | quilt_loader           | /home/alexiil/.gradle/caches/quilt-loom/1.18.2/loom.mappings.1_18_2.layered+hash.917620836-v2/minecraft-merged-named.jar                                                        |                                                                    |                                                                 |                                                 |                                               |                                               |
| MixinExtras                           | com_github_llamalad7_mixinextras       | 0.0.10                | quilted_fabric_loader  | <mods>/twilightforest-fabric-1.19.2-4.2.299.jar                                                                                                                                 | /META-INF/jars/serialization-hooks-0.3.22.jar                      | /META-INF/jars/MixinExtras-0.0.10.jar                           |                                                 |                                               |                                               |
| OpenJDK 64-Bit Server VM              | java                                   | 17                    | quilt_loader           | /usr/lib/jvm/java-17-openjdk-amd64                                                                                                                                              |                                                                    |                                                                 |                                                 |                                               |                                               |
| Porting Lib Accessors                 | porting_lib_accessors                  | 2.0.547+1.19.2        | quilted_fabric_loader  | <mods>/twilightforest-fabric-1.19.2-4.2.299.jar                                                                                                                                 | /META-INF/jars/porting-lib-2.0.547+1.19.2.jar                      | /META-INF/jars/obj_loader-2.0.547+1.19.2.jar                    | /META-INF/jars/model_loader-2.0.547+1.19.2.jar  | /META-INF/jars/extensions-2.0.547+1.19.2.jar  | /META-INF/jars/accessors-2.0.547+1.19.2.jar   |
| Porting Lib Attributes                | porting_lib_attributes                 | 2.0.547+1.19.2        | quilted_fabric_loader  | <mods>/twilightforest-fabric-1.19.2-4.2.299.jar                                                                                                                                 | /META-INF/jars/porting-lib-2.0.547+1.19.2.jar                      | /META-INF/jars/obj_loader-2.0.547+1.19.2.jar                    | /META-INF/jars/model_loader-2.0.547+1.19.2.jar  | /META-INF/jars/extensions-2.0.547+1.19.2.jar  | /META-INF/jars/attributes-2.0.547+1.19.2.jar  |
| Porting Lib Base                      | porting_lib_base                       | 2.0.547+1.19.2        | quilted_fabric_loader  | <mods>/twilightforest-fabric-1.19.2-4.2.299.jar                                                                                                                                 | /META-INF/jars/porting-lib-2.0.547+1.19.2.jar                      | /META-INF/jars/base-2.0.547+1.19.2.jar                          |                                                 |                                               |                                               |
| Porting Lib Common                    | porting_lib_common                     | 2.0.547+1.19.2        | quilted_fabric_loader  | <mods>/twilightforest-fabric-1.19.2-4.2.299.jar                                                                                                                                 | /META-INF/jars/porting-lib-2.0.547+1.19.2.jar                      | /META-INF/jars/transfer-2.0.547+1.19.2.jar                      | /META-INF/jars/common-2.0.547+1.19.2.jar        |                                               |                                               |
| Porting Lib Constants                 | porting_lib_constants                  | 2.0.547+1.19.2        | quilted_fabric_loader  | <mods>/twilightforest-fabric-1.19.2-4.2.299.jar                                                                                                                                 | /META-INF/jars/porting-lib-2.0.547+1.19.2.jar                      | /META-INF/jars/transfer-2.0.547+1.19.2.jar                      | /META-INF/jars/constants-2.0.547+1.19.2.jar     |                                               |                                               |
| Porting Lib Entity                    | porting_lib_entity                     | 2.0.547+1.19.2        | quilted_fabric_loader  | <mods>/twilightforest-fabric-1.19.2-4.2.299.jar                                                                                                                                 | /META-INF/jars/porting-lib-2.0.547+1.19.2.jar                      | /META-INF/jars/entity-2.0.547+1.19.2.jar                        |                                                 |                                               |                                               |
| Porting Lib Extensions                | porting_lib_extensions                 | 2.0.547+1.19.2        | quilted_fabric_loader  | <mods>/twilightforest-fabric-1.19.2-4.2.299.jar                                                                                                                                 | /META-INF/jars/porting-lib-2.0.547+1.19.2.jar                      | /META-INF/jars/obj_loader-2.0.547+1.19.2.jar                    | /META-INF/jars/model_loader-2.0.547+1.19.2.jar  | /META-INF/jars/extensions-2.0.547+1.19.2.jar  |                                               |
| jsr305                                | com_google_code_findbugs_jsr305        | 3.0.2                 | quilted_fabric_loader  | <mods>/twilightforest-fabric-1.19.2-4.2.299.jar                                                                                                                                 | /META-INF/jars/jsr305-3.0.2.jar                                    |                                                                 |                                                 |                                               |                                               |
| minecraft_test                        | minecraft_test                         | 1.0.0                 | quilt_loader           | /home/alexiil/Documents/dev/minecraft/1.12/Quilt-Toolchain/quilt-loader-mod-resolution/minecraft/minecraft-test/bin/main                                                        |                                                                    |                                                                 |                                                 |                                               |                                               |
| toml                                  | com_electronwill_night-config_toml     | 3.6.3                 | quilted_fabric_loader  | <mods>/twilightforest-fabric-1.19.2-4.2.299.jar                                                                                                                                 | /META-INF/jars/toml-3.6.3.jar                                      |                                                                 |                                                 |                                               |                                               |
|---------------------------------------|----------------------------------------|-----------------------|------------------------|---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|--------------------------------------------------------------------|-----------------------------------------------------------------|-------------------------------------------------|-----------------------------------------------|-----------------------------------------------|
```
(Both tables have been shrunk down for clarity - the `Index` column is missing since this was taken from a dev build).

### CODE REVIEW

**Comment by AlexIIL** [comment]
(Draft PR until I work out why I can't build locally)

**Comment by AlexIIL** [comment]
It turns out I wasn't running all the gradle tasks necessary to make it build - I've got a reasonable crash report from the first commit, but it turns out like:
```

	Virtual memory max (MB): 36497.57
	Virtual memory used (MB): 13066.30
	Swap memory total (MB): 20480.00
	Swap memory used (MB): 0.00
	JVM Flags: 8 total; -XX:+UseG1GC -XX:+UnlockExperimentalVMOptions -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M -Xms2048m -Xmx2048m
	Quilt Mods: | Index | Mod                      | ID                | Version               |
|------:|--------------------------|-------------------|-----------------------|
|     0 | Minecraft                | minecraft         | 1.19.2                |
|     2 | OpenJDK 64-Bit Server VM | java              | 18                    |
|     3 | Quilt Base API           | quilt_base        | 3.0.0-beta.19+1.19.2  |
|     1 | Quilt Crash Info         | quilt_crash_info  | 3.0.0-beta.19+1.19.2  |
|     4 | Quilt Loader             | quilt_loader      | 0.17.4                |
|------:|--------------------------|-------------------|-----------------------|

	Launched Version: 1.19.2
	Backend library: LWJGL version 3.3.1 build 7
	Backend API: AMD Radeon RX 580 Series (polaris10, LLVM 13.0.1, DRM 3.42, 5.15.0-50-generic) GL version 4.6 (Core Profile) Mesa 22.0.5, AMD
	Window size: 1920x1052
	GL Caps: Using framebuffer using OpenGL 3.2
```
So I'm rebuilding and retesting after prefixing it with a newline.

**Comment by AlexIIL** [comment]
Okay, now it looks correct :)
```
	Virtual memory max (MB): 36497.57
	Virtual memory used (MB): 13143.49
	Swap memory total (MB): 20480.00
	Swap memory used (MB): 0.00
	JVM Flags: 8 total; -XX:+UseG1GC -XX:+UnlockExperimentalVMOptions -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M -Xms2048m -Xmx2048m
	Quilt Mods: 
| Index | Mod                      | ID                | Version              |
|------:|--------------------------|-------------------|----------------------|
|     0 | Minecraft                | minecraft         | 1.19.2               |
|     2 | OpenJDK 64-Bit Server VM | java              | 18                   |
|     3 | Quilt Base API           | quilt_base        | 3.0.0-alex.1+1.19.2  |
|     1 | Quilt Crash Info         | quilt_crash_info  | 3.0.0-alex.1+1.19.2  |
|     4 | Quilt Loader             | quilt_loader      | 0.17.4               |
|------:|--------------------------|-------------------|----------------------|

	Launched Version: 1.19.2
	Backend library: LWJGL version 3.3.1 build 7
```

**Comment by williambl** [comment]
Neat! Will have a proper look tomorrow 👀

**Review by EnnuiL — APPROVED** [review]

**Review by williambl — APPROVED** [review]

**Review by LambdAurora — APPROVED** [review]
I don't remember if it's possible to have further nesting in a crash report, but oh well, should work fine in most cases.

**Review by ghost — APPROVED** [review]

**Comment by AlexIIL** [comment]
I probably should have commented this earlier - but as of the last commit (https://github.com/QuiltMC/quilt-standard-libraries/pull/202/commits/7fc1d21bc0c011d51f0677c05a72cbd05ae6cf04) it's indented correctly:
```
	Virtual memory max (MB): 36497.57
	Virtual memory used (MB): 14102.72
	Swap memory total (MB): 20480.00
	Swap memory used (MB): 0.00
	JVM Flags: 8 total; -XX:+UseG1GC -XX:+UnlockExperimentalVMOptions -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M -Xms2048m -Xmx2048m
	Quilt Mods: 
		| Index | Mod                      | ID                | Version              |
		|------:|--------------------------|-------------------|----------------------|
		|     0 | Minecraft                | minecraft         | 1.19.2               |
		|     2 | OpenJDK 64-Bit Server VM | java              | 18                   |
		|     3 | Quilt Base API           | quilt_base        | 3.0.0-alex.2+1.19.2  |
		|     1 | Quilt Crash Info         | quilt_crash_info  | 3.0.0-alex.2+1.19.2  |
		|     4 | Quilt Loader             | quilt_loader      | 0.17.5-beta.6        |
		|------:|--------------------------|-------------------|----------------------|
		
	Launched Version: 1.19.2
	Backend library: LWJGL version 3.3.1 build 7
	Backend API: AMD Radeon RX 580 Series (polaris10, LLVM 13.0.1, DRM 3.42, 5.15.0-50-generic) GL version 4.6 (Core Profile) Mesa 22.0.5, AMD
```

**Review by JieningYu — APPROVED** [review]

**Pull request merged**
