### PR TITLE
Implement crash info and add base mod metadata

### PR DESCRIPTION
**Pull request by i509VCB**

### CODE REVIEW

**Review by LambdAurora — APPROVED** [review]

**Review by BasiqueEvangelist — APPROVED** [review]

**Review by pluiedev — APPROVED** [review]

**Review by OroArmor — APPROVED** [review]
I feel like now is the best place to add an api to add sections to the crash report. Otherwise it looks good.

**Review by TheGlitch76 — APPROVED** [review]
please fix style before merging thanks

**Comment by i509VCB** [comment]
Where style? It was always broken in spotless

**Comment by TheGlitch76** [comment]
i meant fix spotless. you might have to comment out the ratchetFrom or something

**Comment by i509VCB** [comment]
Yeah ratcheting seems to be broken in new folders. I'm honestly considering writing my own license tooling since it's now causing issues

**Comment by i509VCB** [comment]
> I feel like now is the best place to add an api to add sections to the crash report. Otherwise it looks good.

I've made an issue regarding that question, respond there.

**Pull request merged**
